version: '3.7'
services:
  grafana:
    container_name: infinityPlugin
    image: grafana/grafana-enterprise:${GF_VERSION:-9.4.3}
    # image: grafana/grafana-enterprise:${GF_VERSION:-8.4.7}
    # image: grafana/grafana-enterprise:${GF_VERSION:-main}
    # image: grafana/grafana-enterprise:${GF_VERSION:-latest}
    ports:
      - '3001:3000'
    volumes:
      - ./provisioning/dashboards-actual/:/dashboards/
      - ./provisioning:/etc/grafana/provisioning
      - ./dist/:/var/lib/grafana/plugins/yesoreyeram-infinity-datasource
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=apofapof
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards topnav dataConnectionsConsole
